# -*- coding: mbcs -*-
#
# Abaqus/CAE Release 2020 replay file
# Internal Version: 2019_09_13-19.49.31 163176
# Run by martinpletz on Thu Oct 19 13:00:42 2023
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=1586.6875, 
    height=1002.10003662109)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from caeModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
cliCommand("""mdb.models.keys()""")
#: ['Model-1']
cliCommand("""mdb.models.values()""")
#: [mdb.models['Model-1']]
cliCommand("""dir(mdb)""")
#: ['AdaptivityProcess', 'Annotation', 'Arrow', 'Coexecution', 'CombineOptResults', 'Job', 'JobFromInputFile', 'Model', 'ModelFromAnsysInputFile', 'ModelFromInputFile', 'ModelFromNastranInputFile', 'ModelFromOdbFile', 'OptimizationProcess', 'Text', '__class__', '__cmp__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'acis', 'adaptivityProcesses', 'annotations', 'close', 'closeAuxMdb', 'coexecutions', 'copyAuxMdbModel', 'getAuxMdbModelNames', 'jobs', 'lastChangedCount', 'meshEditOptions', 'models', 'openAcis', 'openAuxMdb', 'openCatia', 'openEnf', 'openIges', 'openParasolid', 'openProE', 'openSolidworks', 'openStep', 'openVda', 'optimizationProcesses', 'pathName', 'save', 'saveAs', 'setValues', 'version']
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=200.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.rectangle(point1=(-48.75, 17.5), point2=(19.3292846679688, 
    -12.1463108062744))
p = mdb.models['Model-1'].Part(name='Part-1', dimensionality=TWO_D_PLANAR, 
    type=DEFORMABLE_BODY)
p = mdb.models['Model-1'].parts['Part-1']
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
del mdb.models['Model-1'].sketches['__profile__']
session.viewports['Viewport: 1'].view.setValues(nearPlane=146.406, 
    farPlane=150.611, width=81.5202, height=47.055, viewOffsetX=2.3908, 
    viewOffsetY=-0.0469318)
p = mdb.models['Model-1'].parts['Part-1']
e = p.edges
edges = e.getSequenceFromMask(mask=('[#1 ]', ), )
p.Set(edges=edges, name='Set-1')
#: The set 'Set-1' has been created (1 edge).
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
cliCommand("""session.journalOptions.setValues(replayGeometry=COORDINATE,
        		         recoverGeometry=COORDINATE)""")
p = mdb.models['Model-1'].parts['Part-1']
e = p.edges
edges = e.findAt(((19.329285, -4.734733, 0.0), ))
p.Set(edges=edges, name='Set-2')
#: The set 'Set-2' has been created (1 edge).
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
cliCommand("""p = mdb.models['Model-1'].parts['Part-1']""")
cliCommand("""p""")
#: mdb.models['Model-1'].parts['Part-1']
cliCommand("""p.edges.findAt((19.329285, -4.734733, 0.0))""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt((19.329285, -4.734733, 0.0),)
cliCommand("""edg1 = p.edges.findAt((19.329285, -4.734733, 0.0))""")
cliCommand("""p.Set(name='test1', edges=edg1)""")
#* TypeError: keyword error on edges
cliCommand("""type(edg1)""")
#: <type 'Edge'>
cliCommand("""edg2 = p.edges.findAt(((19.329285, -4.734733, 0.0)))""")
cliCommand("""type(edg2)""")
#: <type 'Edge'>
cliCommand("""edg3 = p.edges.findAt(((19.329285, -4.734733, 0.0),))""")
cliCommand("""type(edg3)""")
#: <type 'Sequence'>
cliCommand("""f3 = p.face.findAt(((19.329285, -4.734733, 0.0),))""")
#* AttributeError: 'Part' object has no attribute 'face'
cliCommand("""f3 = p.faces.findAt(((19.329285, -4.734733, 0.0),))""")
cliCommand("""type(f3)""")
#: <type 'Sequence'>
cliCommand("""edg4 = p.edges.findAt(coordinates=((19.329285, -4.734733, 0.0),))""")
cliCommand("""type(edg4)""")
#: <type 'Sequence'>
cliCommand("""edg4 = p.edges.findAt(coordinates=(19.329285, -4.734733, 0.0))""")
cliCommand("""type(edg4)""")
#: <type 'Edge'>
#: Coordinates of vertex 0 :19.329285,17.5,0.
cliCommand("""p.edges.getByBoundingBox(yMin=17.5)""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt(((2.309464, 17.5, 0.0),),)
cliCommand("""p.edges.getByBoundingBox(yMin=17.6)""")
#: ()
cliCommand("""p.edges.getByBoundingBox(yMin=17.5)""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt(((2.309464, 17.5, 0.0),),)
cliCommand("""type(p.edges.getByBoundingBox(yMin=17.5))""")
#: <type 'Sequence'>
cliCommand("""p.edges.getByBoundingBox(yMin=17.5)""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt(((2.309464, 17.5, 0.0),),)
cliCommand("""TOL = 1e-5""")
cliCommand("""p.edges.getByBoundingBox(yMin=17.5-TOL)""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt(((2.309464, 17.5, 0.0),),)
cliCommand("""p.edges.getByBoundingBox(yMin=17.5-TOL)""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt(((2.309464, 17.5, 0.0),),)
p = mdb.models['Model-1'].parts['Part-1']
p.ReferencePoint(point=(5.0, 5.0, 0.0))
session.viewports['Viewport: 1'].view.setValues(nearPlane=145.435, 
    farPlane=151.582, width=90.9324, height=65.7911, viewOffsetX=19.0198, 
    viewOffsetY=4.25716)
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    optimizationTasks=OFF, geometricRestrictions=OFF, stopConditions=OFF)
a = mdb.models['Model-1'].rootAssembly
a.ReferencePoint(point=(0.0, 0.0, 0.0))
session.viewports['Viewport: 1'].view.setValues(nearPlane=3.94946, 
    farPlane=4.05054, width=1.74801, height=1.26471, viewOffsetX=0.0361071, 
    viewOffsetY=-0.24947)
a = mdb.models['Model-1'].rootAssembly
r1 = a.referencePoints
refPoints1=(r1[1], )
a.Set(referencePoints=refPoints1, name='Set-1')
#: The set 'Set-1' has been created (1 reference point).
cliCommand("""rp1 = a.ReferencePoint(point=(0.0, 6, 0.0))""")
#* NameError: name 'a' is not defined
cliCommand("""a = mdb.models['Model-1'].rootAssembly""")
cliCommand("""rp1 = a.ReferencePoint(point=(0.0, 6, 0.0))""")
cliCommand("""rp1""")
#: mdb.models['Model-1'].rootAssembly.features['RP-2']
cliCommand("""a.Set(name='rp', referencePoints=rp1)""")
#* TypeError: referencePoints; found Feature, expecting tuple
cliCommand("""a.Set(name='rp', referencePoints=(rp1,))""")
#* TypeError: referencePoints[0]; found Feature, expecting tuple
cliCommand("""rp1""")
#: mdb.models['Model-1'].rootAssembly.features['RP-2']
cliCommand("""rp1.id""")
#: 3
cliCommand("""a.Set(name='rp', referencePoints=(a.referencePoints[rp1.id],))""")
#: mdb.models['Model-1'].rootAssembly.sets['rp']
session.viewports['Viewport: 1'].view.setValues(nearPlane=3.8598, 
    farPlane=4.1402, width=4.28606, height=3.10104, viewOffsetX=0.0645944, 
    viewOffsetY=0.0693396)
cliCommand("""p""")
#: mdb.models['Model-1'].parts['Part-1']
cliCommand("""type(p.edges)""")
#: <type 'EdgeArray'>
cliCommand("""p.edges[0]""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt((2.309464, 17.5, 0.0),)
cliCommand("""dir(p.edges[0])""")
#: ['__class__', '__cmp__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'featureName', 'getAdjacentEdges', 'getCurvature', 'getEdgesByEdgeAngle', 'getElements', 'getFaces', 'getNodes', 'getRadius', 'getSize', 'getVertices', 'index', 'instanceName', 'isReferenceRep', 'isTangentFlipped', 'pointOn']
cliCommand("""p.edges[0].getSize""")
#: <AbaqusMethod  mdb.models['Model-1'].parts['Part-1'].edges.findAt((2.309464, 17.5, 0.0),).getSize>
cliCommand("""p.edges[0].getSize()""")
#: Length of edge = 68.0792846679688
#: 68.0792846679688
cliCommand("""p.edges[1].getSize()""")
#: Length of edge = 29.6463108062744
#: 29.6463108062744
cliCommand("""p.edges[2].getSize()""")
#: Length of edge = 68.0792846679688
#: 68.0792846679688
cliCommand("""p.edges[3].getSize()""")
#: Length of edge = 29.6463108062744
#: 29.6463108062744
cliCommand("""dir(p.edges[0])""")
#: ['__class__', '__cmp__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'featureName', 'getAdjacentEdges', 'getCurvature', 'getEdgesByEdgeAngle', 'getElements', 'getFaces', 'getNodes', 'getRadius', 'getSize', 'getVertices', 'index', 'instanceName', 'isReferenceRep', 'isTangentFlipped', 'pointOn']
cliCommand("""p.edges[0].featureName""")
#: 'Shell planar-1'
p = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(nearPlane=144.427, 
    farPlane=152.59, width=140.763, height=101.844, viewOffsetX=15.3683, 
    viewOffsetY=3.44496)
p = mdb.models['Model-1'].parts['Part-1']
f, e, d1 = p.faces, p.edges, p.datums
t = p.MakeSketchTransform(sketchPlane=f.findAt(coordinates=(-3.36381, 7.617896, 
    0.0), normal=(0.0, 0.0, 1.0)), sketchPlaneSide=SIDE1, origin=(-14.710358, 
    2.676845, 0.0))
s1 = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=148.5, gridSpacing=3.71, transform=t)
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p = mdb.models['Model-1'].parts['Part-1']
p.projectReferencesOntoSketch(sketch=s1, filter=COPLANAR_EDGES)
s1.CircleByCenterPerimeter(center=(-10.4495998857422, 2.38704259613037), 
    point1=(3.99347720166016, 0.0663047573852538))
p = mdb.models['Model-1'].parts['Part-1']
f = p.faces
pickedFaces = f.findAt(((-3.36381, 7.617896, 0.0), ))
e1, d2 = p.edges, p.datums
p.PartitionFaceBySketch(faces=pickedFaces, sketch=s1)
s1.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__profile__']
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=ON, 
    constraints=ON, connectors=ON, engineeringFeatures=ON)
p = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(nearPlane=144.595, 
    farPlane=152.422, width=117.15, height=84.7603, viewOffsetX=5.47897, 
    viewOffsetY=-2.68636)
cliCommand("""p.edges[0].featureName""")
#: 'Partition face-1'
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
a=mdb.models['Model-1'].parts['Part-1']
a.SetByBoolean(name='Set-3', sets=(a.sets['Set-2'], a.sets['Set-1'], ))
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
cliCommand("""p.edges.getClosest(((17.5,5,0),))""")
#: {0: (mdb.models['Model-1'].parts['Part-1'].edges.findAt((19.329285, -4.734733, 0.0),), (19.3292846679688, 5.0, 0.0))}
cliCommand("""p.edges.getClosest(((17.5,5,0),))[0]""")
#: (mdb.models['Model-1'].parts['Part-1'].edges.findAt((19.329285, -4.734733, 0.0),), (19.3292846679688, 5.0, 0.0))
cliCommand("""p.edges.getClosest(((17.5,5,0),))[0][0]""")
#: mdb.models['Model-1'].parts['Part-1'].edges.findAt((19.329285, -4.734733, 0.0),)
cliCommand("""edg_closest = p.edges.getClosest(((17.5,5,0),))[0][0]""")
cliCommand("""p.Set(name='close', edges=closest)""")
#* NameError: name 'closest' is not defined
cliCommand("""p.Set(name='close', edges=edg_closest)""")
#* TypeError: keyword error on edges
cliCommand("""highlight(p.edges.getClosest(((17.5,5,0),))[0][0])""")
p1 = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
cliCommand("""highlight(p.edges.getClosest(((17.5,5,0),))[0][0])""")
session.viewports['Viewport: 1'].view.setValues(nearPlane=145.339, 
    farPlane=151.678, width=93.8205, height=67.8807, viewOffsetX=3.1642, 
    viewOffsetY=-0.351727)
cliCommand("""p.Set(name='close', edges=edg_closest)""")
#* TypeError: keyword error on edges
cliCommand("""dir(p)""")
#: ['AddCells', 'AddFaces', 'AnalyticRigidSurf2DPlanar', 'AnalyticRigidSurfExtrude', 'AnalyticRigidSurfRevolve', 'AssignMidsurfaceRegion', 'AttachmentLines', 'AttachmentPoints', 'AttachmentPointsAlongDirection', 'AttachmentPointsOffsetFromEdges', 'AutoRepair', 'BaseShell', 'BaseShellExtrude', 'BaseShellRevolve', 'BaseShellSweep', 'BaseSolidExtrude', 'BaseSolidRevolve', 'BaseSolidSweep', 'BaseWire', 'BlendFaces', 'Chamfer', 'CompositeLayup', 'ConvertToAnalytical', 'ConvertToPrecise', 'CopyCompressFeatureList', 'CoverEdges', 'CreateHealedPart', 'Cut', 'CutExtrude', 'CutLoft', 'CutRevolve', 'CutSweep', 'DatumAxisByCylFace', 'DatumAxisByNormalToPlane', 'DatumAxisByParToEdge', 'DatumAxisByPrincipalAxis', 'DatumAxisByRotation', 'DatumAxisByThreePoint', 'DatumAxisByThruEdge', 'DatumAxisByTwoPlane', 'DatumAxisByTwoPoint', 'DatumCsysByDefault', 'DatumCsysByOffset', 'DatumCsysByThreePoints', 'DatumCsysByTwoLines', 'DatumPlaneByLinePoint', 'DatumPlaneByOffset', 'DatumPlaneByPointNormal', 'DatumPlaneByPrincipalPlane', 'DatumPlaneByRotation', 'DatumPlaneByThreePoints', 'DatumPlaneByTwoPoint', 'DatumPointByCoordinate', 'DatumPointByEdgeParam', 'DatumPointByMidPoint', 'DatumPointByOffset', 'DatumPointByOnFace', 'DatumPointByProjOnEdge', 'DatumPointByProjOnFace', 'EditSkin', 'EditStringer', 'Element', 'Elements', 'ExtendFaces', 'FaceFromElementFaces', 'GeometrySurface', 'HoleBlindFromEdges', 'HoleFromEdges', 'HoleThruAllFromEdges', 'InterestingPoint', 'Lock', 'LockForUpgrade', 'MakePlacement', 'MakeSketchTransform', 'MapSetsFromOdb', 'MaterialOrientation', 'MergeEdges', 'MeshSurface', 'MeshSurfaceFromElsets', 'MeshSurfaceFromLabels', 'Mirror', 'Node', 'Nodes', 'OffsetFaces', 'PartFromMesh', 'PartitionCellByDatumPlane', 'PartitionCellByExtendFace', 'PartitionCellByExtrudeEdge', 'PartitionCellByPatchNCorners', 'PartitionCellByPatchNEdges', 'PartitionCellByPlaneNormalToEdge', 'PartitionCellByPlanePointNormal', 'PartitionCellByPlaneThreePoints', 'PartitionCellBySketch', 'PartitionCellBySweepEdge', 'PartitionEdgeByDatumPlane', 'PartitionEdgeByParam', 'PartitionEdgeByPoint', 'PartitionFaceByAuto', 'PartitionFaceByCurvedPathEdgeParams', 'PartitionFaceByCurvedPathEdgePoints', 'PartitionFaceByDatumPlane', 'PartitionFaceByExtendFace', 'PartitionFaceByIntersectFace', 'PartitionFaceByProjectingEdges', 'PartitionFaceByShortestPath', 'PartitionFaceBySketch', 'PartitionFaceBySketchDistance', 'PartitionFaceBySketchRefPoint', 'PartitionFaceBySketchThruAll', 'ReferencePoint', 'Reinforcement', 'RemoveAttachments', 'RemoveCells', 'RemoveEdges', 'RemoveFaces', 'RemoveFacesAndStitch', 'RemoveRedundantEntities', 'RemoveVertices', 'RemoveWireEdges', 'RenameSet', 'RepairFaceNormals', 'RepairInvalidEdges', 'RepairSliver', 'RepairSmallEdges', 'RepairSmallFaces', 'ReplaceFaces', 'Round', 'SectionAssignment', 'Set', 'SetByBoolean', 'SetByMerge', 'SetFromColor', 'SetFromElementLabels', 'SetFromNodeLabels', 'Shell', 'ShellCutRevolve', 'ShellExtrude', 'ShellLoft', 'ShellRevolve', 'ShellSweep', 'Skin', 'SolidExtrude', 'SolidLoft', 'SolidRevolve', 'SolidSweep', 'Stitch', 'Stringer', 'Surface', 'SurfaceByBoolean', 'SurfaceByMerge', 'SurfaceFromElsets', 'SurfaceFromLabels', 'Unlock', 'VariableRadiusRound', 'Wire', 'WireFromEdge', 'WirePolyLine', 'WireSpline', 'WireTwoPoints', '__class__', '__cmp__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'addGeomToSketch', 'adjustMidsideNode', 'allInternalSets', 'allInternalSurfaces', 'allSets', 'allSurfaces', 'assignBeamSectionOrientation', 'assignMaterialOrientation', 'assignRebarOrientation', 'assignStackDirection', 'assignThickness', 'associateMeshWithGeometry', 'backup', 'beamSectionOrientations', 'cells', 'checkGeometry', 'clashSets', 'cleanMesh', 'clearGeometryCache', 'collapseMeshEdge', 'combineElement', 'compositeLayups', 'convertSolidMeshToShell', 'copyMeshPattern', 'createVirtualTopology', 'datum', 'datums', 'deleteAllFeatures', 'deleteBoundaryLayerControls', 'deleteElement', 'deleteFeatures', 'deleteMesh', 'deleteMeshAssociationWithGeometry', 'deleteNode', 'deleteSeeds', 'deleteSets', 'deleteSurfaces', 'edges', 'editNode', 'elemEdges', 'elemFaces', 'elementEdges', 'elementFaces', 'elements', 'engineeringFeatures', 'faces', 'featurelistInfo', 'features', 'featuresById', 'flipNormal', 'flipTangent', 'generateBottomUpExtrudedMesh', 'generateBottomUpRevolvedMesh', 'generateBottomUpSweptMesh', 'generateMesh', 'generateMeshByOffset', 'geometryPrecision', 'geometryRefinement', 'geometryValidity', 'getAngle', 'getArea', 'getAssociatedCADPaths', 'getCADParameters', 'getCentroid', 'getCoordinates', 'getCurvature', 'getDistance', 'getEdgeSeeds', 'getElementType', 'getFeatureCells', 'getFeatureEdges', 'getFeatureFaces', 'getFeatureVertices', 'getIncompatibleMeshInterfaces', 'getLength', 'getMassProperties', 'getMeshControl', 'getMeshStats', 'getPartSeeds', 'getPerimeter', 'getPosition', 'getUnmeshedRegions', 'getVolume', 'ignoreEntity', 'ignoredEdges', 'ignoredVertices', 'insertElements', 'ips', 'isAlignedWithSketch', 'isLocked', 'isOutOfDate', 'isSetInternal', 'isSurfaceInternal', 'markSetInternal', 'markSurfaceInternal', 'materialOrientations', 'mergeElement', 'mergeNodes', 'modelName', 'name', 'nodes', 'orientElements', 'printAssignedSections', 'projectEdgesOntoSketch', 'projectNode', 'projectOntoSketch', 'projectReferencesOntoSketch', 'queryAttributes', 'queryCachedStates', 'queryDisjointPlyRegions', 'queryGeometry', 'queryProperties', 'queryRegionsMissingSections', 'queryVolumeProperties', 'rebarOrientations', 'redoMeshEdit', 'referencePoints', 'regenerate', 'regenerationWarnings', 'reinforcements', 'removeElementSize', 'removeInvalidGeometry', 'renumberElement', 'renumberNode', 'repair', 'replaceMesh', 'restore', 'restoreIgnoredEntity', 'resumeAllFeatures', 'resumeFeatures', 'resumeLastSetFeatures', 'retainedNodes', 'saveGeometryCache', 'sectionAssignments', 'seedEdgeByBias', 'seedEdgeByNumber', 'seedEdgeBySize', 'seedPart', 'setAssociatedCADPaths', 'setBoundaryLayerControls', 'setElementSize', 'setElementType', 'setLogicalCorners', 'setMeshControls', 'setPrimaryObject', 'setSeedConstraints', 'setSweepPath', 'setValues', 'sets', 'skins', 'smoothNodes', 'space', 'splitElement', 'splitMeshEdge', 'stringers', 'subdivideElement', 'suppressFeatures', 'surfaces', 'swapMeshEdge', 'timeStamp', 'trimMesh', 'twist', 'type', 'unassignBeamSectionOrientation', 'unassignMaterialOrientation', 'unassignRebarOrientation', 'undoMeshEdit', 'verifyMeshQuality', 'vertices', 'wrapMesh', 'writeAcisFile', 'writeCADParameters', 'writeHealedPart', 'writeIgesFile', 'writeStepFile', 'writeVdaFile']
cliCommand("""dir(p.edges)""")
#: ['__add__', '__class__', '__cmp__', '__delattr__', '__delitem__', '__delslice__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__init__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setitem__', '__setslice__', '__sizeof__', '__str__', '__subclasshook__', 'findAt', 'getBoundingBox', 'getByBoundingBox', 'getByBoundingCylinder', 'getByBoundingSphere', 'getClosest', 'getMask', 'getSequenceFromMask', 'index', 'pointsOn']
cliCommand("""dir(part)""")
#* NameError: name 'part' is not defined
cliCommand("""from caseModules import *""")
#* ImportError: No module named caseModules
cliCommand("""from caeModules import *""")
cliCommand("""dir(part)""")
#: ['ABAQUS_ADV2K', 'ABAQUS_AEMDB_SIDE', 'ABAQUS_AQUA', 'ABAQUS_BIORID', 'ABAQUS_CEL', 'ABAQUS_CFD', 'ABAQUS_DESIGN', 'ABAQUS_EEVC', 'ABAQUS_EXPLICIT', 'ABAQUS_HEADFORM_PEEVC', 'ABAQUS_HMNTCS_EMHF', 'ABAQUS_HMNTCS_ES2', 'ABAQUS_HMNTCS_ES2RE', 'ABAQUS_HMNTCS_FLEXPLI', 'ABAQUS_HMNTCS_H305', 'ABAQUS_HMNTCS_H305_BLST', 'ABAQUS_HMNTCS_H350', 'ABAQUS_HMNTCS_H350_BLST', 'ABAQUS_HMNTCS_H395', 'ABAQUS_HMNTCS_H395_BLST', 'ABAQUS_HMNTCS_Q10', 'ABAQUS_HMNTCS_Q6', 'ABAQUS_HMNTCS_SID2S_SBLC', 'ABAQUS_HMNTCS_SID2S_SBLD', 'ABAQUS_IIHS', 'ABAQUS_NHTSA', 'ABAQUS_STANDARD', 'ABAQUS_TRL_FWDB_FRONT', 'ABAQUS_WORLDSID', 'ACOUSTICS', 'ACTIVE_CUT_RANGE', 'ADAPTIVE_MESHING', 'ADAPTIVE_MESH_SMOOTHING_FAILED', 'AFTER', 'ALL', 'ALL_EDGES', 'AMPLITUDE', 'ANALYTIC_RIGID_SURFACE', 'ANGULAR', 'ANNEALING', 'AQUA', 'ARC_LENGTH', 'ARRAY_1D', 'ARROW', 'ASSEMBLY_LOAD', 'ATTACH_TO_REGION', 'AUGMENTED_LAGRANGE_INCOMPATIBILITIES', 'AUTOCAD', 'AUTO_FIT', 'AUTO_FIT_PTS', 'AUTO_INCREMENTATION', 'AVERAGE', 'AXIAL_FORCE_CONSTRAINT', 'AXISYM', 'AXISYMMETRIC', 'AXIS_1', 'AXIS_2', 'AXIS_3', 'AccessError', 'AcisType', 'AnalyticSurfaceProfile', 'AnalyticSurfaceSegment', 'BEFORE', 'BOOLEAN', 'BOTH', 'BOTHSIDES', 'BOTH_SIDES', 'BOTH_SURFACES', 'BOTTOM', 'BOTTOM_CENTER', 'BOTTOM_LEFT', 'BOTTOM_RIGHT', 'BOTTOM_SURFACE', 'BOUNDARY_CONDITION', 'BOX_OFF', 'BOX_ON', 'BY_NUMBER', 'BY_SPACING', 'BackwardCompatibilityType', 'BasicOptionsType', 'CARTESIAN', 'CATEGORY_BASED', 'CAVITY_RADIATION', 'CAVITY_RADIATION_EMMISIVITY_TOO_LARGE', 'CAVITY_RADIATION_PARALLEL_DECOMPOSITION', 'CENTER', 'CENTER_LEFT', 'CENTER_OF_MASS', 'CENTER_RIGHT', 'CENTROID', 'CIRCLE', 'CIRCUM', 'CIRCUMF', 'CIRC_MIRROR_RECT', 'CIRC_RECT_MIRROR', 'CLOCKWISE', 'CLOSEST', 'CLOSEST_POINT_FRACTION', 'COARSE', 'COMPLEX_EIGENSOLVER', 'COMPLEX_ENVELOPE_MAX', 'COMPLEX_ENVELOPE_MAX_ABS', 'COMPLEX_ENVELOPE_MIN', 'COMPLEX_MAGNITUDE', 'COMPLEX_PHASE', 'COMPLEX_VAL_AT_ANGLE', 'COMPONENT', 'CONNECTOR', 'CONSTANT', 'CONSTRAINT', 'CONTINUOUS', 'CONTOURS_ON_DEF', 'CONTOURS_ON_UNDEF', 'CONVERGENCE', 'COPLANAR_EDGES', 'CORRECTION_ACCEPTED', 'CORRECTION_ACCEPTED_ESTIMATED_CORRECTION', 'CORRECTION_ACCEPTED_SMALL_INCREMENT', 'CORRECTION_NOT_ACCEPTED', 'COUNTERCLOCKWISE', 'COUPLED_THERMAL_ELECTRICAL', 'COUPLED_THERMAL_STRESS', 'COUPLING_FORCE_CONSTRAINT', 'COUPLING_MOMENT_CONSTRAINT', 'CPU_TIME_XPL', 'CROSSED_SURFACES', 'CSYS', 'CUBIC_SPLINE', 'CURRENT_DISPLAY_GROUP', 'CURRENT_FRAME', 'CYCLIC_SYMMETRY', 'CYLINDER', 'CYLINDRICAL', 'CellArray', 'CellArrayType', 'CellType', 'ConnectorOrientationArrayType', 'ConnectorOrientationIntObjType', 'CouplingConstraintType', 'DASHED', 'DEBONDING', 'DEFAULT', 'DEFORMABLE_BODY', 'DEFORMED', 'DESIGN_SENSITIVITY', 'DIFFERENCE', 'DIRECT_CYCLIC', 'DIRECT_INCREMENTATION', 'DIRECT_NO_STOP_INCREMENTATION', 'DIRECT_SOLVER', 'DIRECT_STEADY_STATE_DYNAMIC', 'DISCONTINUITIES', 'DISCRETE_RIGID_SURFACE', 'DISK', 'DISPLACEMENT_FIELD', 'DISPLAY_GROUP', 'DISPLAY_GROUPS', 'DISTRIBUTING_COUPLING', 'DMASS_XPL', 'DOTTED', 'DOT_DASH', 'DOUBLE', 'DOUBLE_PRECISION', 'DOUBLE_SIDED', 'DatumAxisType', 'DatumCsysType', 'DatumPlaneType', 'DatumPointType', 'DatumType', 'EDGE1', 'EDGE10', 'EDGE11', 'EDGE12', 'EDGE13', 'EDGE14', 'EDGE15', 'EDGE16', 'EDGE17', 'EDGE18', 'EDGE19', 'EDGE2', 'EDGE20', 'EDGE3', 'EDGE4', 'EDGE5', 'EDGE6', 'EDGE7', 'EDGE8', 'EDGE9', 'EIGENVALUE_BUCKLING', 'ELECTRICAL_CONTACT', 'ELECTRICAL_POTENTIAL_FIELD', 'ELECTRIC_POTENTIAL_ELECTROLYTE_', 'ELEMENT', 'ELEMENT_BY_ELEMENT_INCREMENTATION', 'ELEMENT_CENTROID', 'ELEMENT_FACE', 'ELEMENT_FACE_INTEGRATION_POINT', 'ELEMENT_NODAL', 'ELEMENT_SET', 'EMBEDDED_ELEMENT', 'EMPTY_FIELD', 'ENABLED', 'END', 'END1', 'END2', 'END3', 'END_RELEASE', 'ENUMERATION', 'EQUATION', 'ETOTAL_XPL', 'EULERIAN', 'EXACT', 'EXCESSIVE_DISTORTION', 'EXCESSIVE_ELEMENT_DISTORTION', 'EXCESSIVE_STRAIN_INCREMENT', 'EXPLICIT_DYNAMIC', 'EXTRAPOLATE_AVERAGE_COMPUTE', 'EXTRAPOLATE_COMPUTE', 'EXTRAPOLATE_COMPUTE_AVERAGE', 'EXTRAPOLATE_COMPUTE_DISCONTINUITIES', 'EXTRA_COARSE', 'EXTRA_FINE', 'EdgeArray', 'EdgeArrayType', 'EdgeType', 'EngineeringFeatureDisplayOptionsType', 'FACE1', 'FACE2', 'FACE3', 'FACE4', 'FACE5', 'FACE6', 'FACE_UNKNOWN', 'FARTHEST_POINT_FRACTION', 'FASTENER', 'FIELD', 'FIELD_OUTPUT', 'FILLED_ARROW', 'FILLED_CIRCLE', 'FILLED_DIAMOND', 'FILLED_SQUARE', 'FINE', 'FIRST_FRAME', 'FIXED_INCREMENTATION', 'FLOAT', 'FLUID_PRESSURE_FIELD', 'FORWARD', 'FRACTURE_MECHANICS', 'FRAME_VALUE', 'FREQUENCY', 'FROM_ASCII_FILE', 'FROM_KEYBOARD', 'FROM_ODB', 'FROM_OPERATION', 'FROM_USER_DEFINED', 'FULL_FIELD', 'FaceArray', 'FaceArrayType', 'FaceType', 'FeatureError', 'FeatureOptionsType', 'FeatureSketchType', 'FeatureType', 'FieldLocationArrayType', 'FieldLocationType', 'FieldOutputType', 'FieldValueArrayType', 'FieldValueType', 'GENERAL_PARTICLE', 'GEOMETRY', 'GLOBAL', 'GROUND', 'GeometryDisplayOptionsType', 'HALF_OF_AVERAGE', 'HEALER_TYPE', 'HEAT_TRANSFER', 'HEX20', 'HEX8', 'HOLLOW_CIRCLE', 'HOLLOW_DIAMOND', 'HOLLOW_SQUARE', 'HYBRID', 'HYDROSTATIC_FLUID_MODELING', 'HYSTERESIS_INITIAL_GUESSES_EXHAUSTED', 'HYSTERESIS_JACOBIAN_CANNOT_BE_INVERTED', 'HistoryOutputType', 'HistoryPoint', 'HistoryPointType', 'HistoryRegionType', 'HistoryVariableType', 'IMAGINARY', 'IMPERFECTION', 'IMPLICIT_DYNAMIC', 'IMPORT', 'IMPRINT', 'INCREMENTATION', 'INC_SIZE', 'INDEX', 'INERTIA_RELIEF', 'INITIAL_CONDITION', 'INITIAL_OPENINGS', 'INITIAL_OVERCLOSURES', 'INITIAL_OVERCLOSURES_EXPLICIT', 'INPUT', 'INTEGER', 'INTEGRATION_POINT', 'INTERNAL', 'INTERSECTION', 'INV3', 'INVALID', 'INVALID_SURF', 'INVARIANT', 'INWARD', 'ION_CONCENTRATION_FIELD', 'IPArrayType', 'IPType', 'ISOSURFACE', 'ITERATIVE_SOLVER', 'IgnoredEdgeArrayType', 'IgnoredEdgeType', 'IgnoredVertexArrayType', 'IgnoredVertexType', 'InterestingPointType', 'JAMA', 'JOB_STATUS_COMPLETED_SUCCESSFULLY', 'JOB_STATUS_EXITED_WITH_ERROR', 'JOB_STATUS_TERMINATED_BY_EXTERNAL_REQUEST', 'JOB_STATUS_UNKNOWN', 'JobDataType', 'KINEMATIC_COUPLING', 'KINEMATIC_VIOLATIONS', 'KINETIC_ENERGY_XPL', 'LANCZOS_EIGENSOLVER', 'LARGE_STRAIN_INCREMENT', 'LAST_FRAME', 'LATERAL_EXTENSION_RATIO_NOT_FOUND', 'LAYUP', 'LAYUP_ORIENTATION', 'LEFT', 'LICENSING', 'LINE', 'LINE2', 'LINE3', 'LINEAR', 'LINEAR_EXTRAPOLATION', 'LINE_SEARCH', 'LOAD', 'LOAD_CASE', 'LoftSection', 'LoftSectionType', 'MAGNITUDE', 'MAGNITUDE_AND_PHASE', 'MASS_DIFFUSION', 'MASS_SCALING', 'MATCH', 'MATERIAL', 'MATERIAL_FLOW_FIELD', 'MATERIAL_INSTABILITY', 'MATERIAL_POINT_CALCULATIONS', 'MATRIX', 'MAXIMUM_NUMBER_OF_CONTACT_STRESS_AUGMENTATIONS', 'MAXIMUM_NUMBER_OF_EQUILIBRIUM_ITERATIONS', 'MAXIMUM_NUMBER_OF_SEVERE_DISCONTINUITY_ITERATIONS', 'MAXIMUM_SLIDE_DISTANCE_EXCEEDED', 'MAX_ABS_VALUE', 'MAX_CORRECTION', 'MAX_ERROR', 'MAX_INCREMENT', 'MAX_INPLANE_PRINCIPAL', 'MAX_PRINCIPAL', 'MAX_RESIDUAL', 'MAX_VALUE', 'MECHANICAL_CONTACT', 'MEDIUM', 'MEMORY', 'MERGE', 'MESH', 'MESHED_BEAM_SECTION', 'MESH_TIE', 'MIDDLE', 'MID_PRINCIPAL', 'MIN_INPLANE_PRINCIPAL', 'MIN_PRINCIPAL', 'MIN_VALUE', 'MIRROR', 'MIRROR_CIRC_RECT', 'MIRROR_RECT_CIRC', 'MISES', 'MIXED', 'MODAL', 'MODEL_CHANGE', 'MODEL_SIZE', 'MODE_BASED_DYNAMIC', 'MODE_BASED_STEADY_STATE_DYNAMIC', 'MPC', 'MSBO', 'MSPEI_XPL', 'MappingCurve', 'MappingCurveType', 'MeshDisplayOptionsType', 'MeshEdgeArrayType', 'MeshEdgeType', 'MeshEditOptionsType', 'MeshElementArrayType', 'MeshElementType', 'MeshFaceArrayType', 'MeshFaceType', 'MeshNodeArrayType', 'MeshNodeType', 'MpcConstraintType', 'N1_COSINES', 'NATURAL_FREQUENCY_EXTRACTION', 'NEW_CONTACT_PATCH', 'NODAL', 'NODE', 'NONE', 'NORMAL', 'NORMALIZED_CONCENTRATION_FIELD', 'NO_EXTRAPOLATION', 'NO_HEAD', 'NO_INITIAL_INTERSECTION', 'NO_LINE', 'NO_REFINEMENT', 'NUMERICAL_PROBLEM', 'NUM_ATTEMPTS', 'NUM_DATA_TYPE', 'NUM_ELEMENTS_EXCEEDING', 'NUM_EQI', 'NUM_ITERS', 'NUM_PTS_ALONG_DIR', 'NUM_PTS_BETWEEN_PTS', 'NUM_SDI', 'NodalDofsArrayType', 'ODB_REGIONS', 'ODB_VALUES', 'OPENINGS', 'ORIENTATION', 'ORIENT_ON_DEF', 'ORIENT_ON_UNDEF', 'OTHER', 'OUTOFPLANE_PRINCIPAL', 'OUTPUT', 'OUTWARD', 'OUT_OF_PLANE_EXTENSION_RATIO_NOT_FOUND', 'OVERCLOSURES', 'OVERCONSTRAINT', 'Odb', 'OdbAnalysisErrorSeqType', 'OdbAnalysisErrorType', 'OdbAnalysisWarningSeqType', 'OdbAnalysisWarningType', 'OdbAnalyticSurfaceSegmentArrayType', 'OdbAnalyticSurfaceSegmentType', 'OdbAnalyticSurfaceType', 'OdbAssemblyType', 'OdbAuxiliaryDataSeqType', 'OdbAuxiliaryDataType', 'OdbCompatibilityErrorSeqType', 'OdbCompatibilityErrorType', 'OdbContactDiagnosticSeqType', 'OdbContactDiagnosticType', 'OdbContactIterationSeqType', 'OdbContactIterationType', 'OdbDataDatumCsysType', 'OdbDataElementSetType', 'OdbDataElementTypeType', 'OdbDataFrameType', 'OdbDataInstanceType', 'OdbDataMaterialType', 'OdbDataNodeSetType', 'OdbDataSectionType', 'OdbDataStepType', 'OdbDataSurfaceSetType', 'OdbDataType', 'OdbDatumCsysType', 'OdbDiagnosticAttemptSeqType', 'OdbDiagnosticAttemptType', 'OdbDiagnosticDataType', 'OdbDiagnosticIncrementSeqType', 'OdbDiagnosticIncrementType', 'OdbDiagnosticIterationSeqType', 'OdbDiagnosticIterationType', 'OdbDiagnosticStepSeqType', 'OdbDiagnosticStepType', 'OdbElementDiagnosticSeqType', 'OdbElementDiagnosticType', 'OdbError', 'OdbFrameArrayType', 'OdbFrameType', 'OdbIncrementStatusType', 'OdbInstanceType', 'OdbJobTimeType', 'OdbLoadCaseType', 'OdbMeshElementArrayType', 'OdbMeshElementType', 'OdbMeshNodeArrayType', 'OdbMeshNodeType', 'OdbNumericalProblemSummaryType', 'OdbPretensionSectionArrayType', 'OdbPretensionSectionType', 'OdbResidualSeqType', 'OdbResidualType', 'OdbRigidBodyArrayType', 'OdbRigidBodyType', 'OdbSequenceAnalysisErrorType', 'OdbSequenceAnalysisWarningType', 'OdbSequenceAuxiliaryDataType', 'OdbSequenceCompatibilityErrorType', 'OdbSequenceContactDiagnosticType', 'OdbSequenceContactIterationType', 'OdbSequenceDiagnosticAttemptType', 'OdbSequenceDiagnosticIncrementType', 'OdbSequenceDiagnosticIterationType', 'OdbSequenceDiagnosticStepType', 'OdbSequenceElementDiagnosticType', 'OdbSequenceResidualType', 'OdbSetType', 'OdbStepType', 'OdbType', 'OdiError', 'PARABOLA', 'PARABOLIC_EXTRAPOLATION', 'PARALLEL', 'PARAMETRIC_DATA', 'PARTIAL_FIELD', 'PATTERN_ALONG_DIRECTION', 'PATTERN_INVALID', 'PATTERN_ORTHOGONALLY', 'PENETRATION_TOLERANCE_EXCEEDED', 'PERPENDICULAR', 'PIEZOELECTRIC', 'PIEZO_ELECTRICAL_POTENTIAL_FIELD', 'PLANE', 'PLY', 'PLY_BASED', 'POINTS_NOW_SLIPPING', 'POINTS_NOW_STICKING', 'PORE_CONCENTRATION_SLURRY_', 'PORE_FLUID_CONTACT', 'PORE_FLUID_DIFFUSION', 'PORE_LIQUID_PRESSURE_FIELD', 'PREDEFINED_FIELD', 'PREDEFINED_PATH', 'PRESS', 'PRESSURE_PENETRATION', 'PRESSURE_STRESS_CONSTRAINT', 'PROJECT_BY_DIRECTION', 'PROJECT_BY_DISTANCE', 'PROJECT_BY_NUMBER', 'PROJECT_BY_PROXIMITY', 'PYR5', 'PartDisplayOptionsType', 'PartElemLabelsLeafType', 'PartNodeLabelsLeafType', 'PartType', 'PartitionType', 'PickingExpressionType', 'QUAD', 'QUAD4', 'QUAD8', 'QUADRATIC', 'QUAD_DOMINATED', 'QUASI_NEWTON_METHOD', 'QUASI_STATIC', 'QUATERNION_2D', 'QUATERNION_3D', 'RADIAL', 'RANDOM_RESPONSE', 'RATE_OF_CONVERGENCE_IS_SLOW', 'RAW_DATA', 'REAL', 'REAL_AND_IMAGINARY', 'RECOMPUTE_GEOMETRY', 'RECT_CIRC_MIRROR', 'RECT_MIRROR_CIRC', 'REGULAR', 'REINFORCEMENT', 'REPETITIVE_SDI_PATTERN', 'RESIDUAL_ACCEPTED', 'RESIDUAL_NOT_ACCEPTED', 'RESPONSE_SPECTRUM', 'RESTART', 'REVERSE', 'REVERSE_MIRROR', 'REVOLUTION', 'RIGHT', 'RIGID_BODY', 'RIKS', 'ROTATE', 'ROTATION_FIELD', 'ReferencePointType', 'RefinerType', 'Region', 'RegionType', 'RepositoryType', 'RigidBodyConstraintType', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'SCALAR', 'SCREEN_SIZE', 'SECTION', 'SEGMENTS', 'SELECT_ALL', 'SELECT_BY_ANGLE', 'SELECT_BY_NUMBER', 'SEPARATE', 'SEPARATED_SOLUTION', 'SEQUENTIAL_THERMAL_STRESS', 'SEVERE_CONTACT_OVERCLOSURES', 'SEVERE_OVERCLOSURES', 'SHARED_DUMMY_FIELD', 'SHARED_LM_PRESSURE_FIELD', 'SHARED_LM_VOLUME_FIELD', 'SHELL', 'SHELL_TO_SOLID_COUPLING', 'SHORTEST_PATH', 'SIDE1', 'SIDE2', 'SINGLE_PRECISION', 'SLIDE_DISTANCE_EXCEEDED', 'SLIPPED_OFF_PATCH', 'SNEG', 'SOFT_CONTACT_INCOMPATIBILITIES', 'SOLID', 'SOLIDWORKS', 'SOLUTION_APPEARS_TO_BE_DIVERGING', 'SPECIFIED', 'SPECIFY_NUM_PTS', 'SPECIFY_PATH', 'SPECTRUM', 'SPHERE', 'SPHERICAL', 'SPOS', 'STABILIZATION', 'STABLE_INC_XPL', 'STANDALONE', 'STANDALONENOSHOW', 'STANDARD', 'START', 'STATIC', 'STATIC_PERTURBATION', 'STEADY_STATE_TRANSPORT', 'STEP_TIME', 'STEP_TIME_XPL', 'STRAIN_FREE_CORRECTIONS', 'SUBMODELING', 'SUBSPACE_DYNAMIC', 'SUBSPACE_EIGENSOLVER', 'SUBSPACE_STEADY_STATE_DYNAMIC', 'SUBSTRUCTURING', 'SUPERIMPOSE', 'SURFACE', 'SURFACE_INTEGRATION_POINT', 'SURFACE_NODAL', 'SYMBOLS_ON_DEF', 'SYMBOLS_ON_UNDEF', 'SYMMETRIC_MODEL_GENERATION', 'SectionAssignmentArrayType', 'SectionAssignmentIntObjType', 'SectionCategoryType', 'SectionPointArrayType', 'SectionPointType', 'SetType', 'ShellSolidCouplingConstraintType', 'Sketch', 'SketchDimensionType', 'SketchGeometryType', 'SketchOptionsType', 'SketchTransform', 'SketchTransformType', 'SketchType', 'SketchVertexType', 'SketcherOptionsType', 'SurfaceType', 'TANGENT', 'TANGENTIAL', 'TEMPERATURE_FALLEN_BELOW_ABSOLUTE_ZERO', 'TEMPERATURE_FIELD', 'TENSOR', 'TENSOR_2D_PLANAR', 'TENSOR_2D_SURFACE', 'TENSOR_3D_FULL', 'TENSOR_3D_PLANAR', 'TENSOR_3D_SURFACE', 'TESSELLATED', 'TET', 'TET10', 'TET4', 'TEXTURE_MAPPED', 'THERMAL_CONTACT', 'THREED_DATA', 'THREE_D', 'TIE', 'TIGHTEN_GAPS', 'TIME', 'TIME_AVERAGE', 'TIME_INTEGRATION', 'TIME_INTEGRATION_ACCURACY_LIMIT_EXCEEDED', 'TIME_INTEGRATION_STABILITY_LIMIT_EXCEEDED', 'TOP', 'TOP_AND_BOTTOM', 'TOP_CENTER', 'TOP_LEFT', 'TOP_RIGHT', 'TOP_SURFACE', 'TOTAL_MASS_XPL', 'TOTAL_NUM', 'TOTAL_TIME_XPL', 'TRANSFORMATION', 'TRANSLATE', 'TRANSPARENT', 'TRANSVERSE_SHEAR_FORCE_CONSTRAINT', 'TRESCA', 'TRI', 'TRI3', 'TRI6', 'TWO_D_PLANAR', 'TieConstraintType', 'TransformType', 'UNCONVERGED_CAP_PLASTICITY', 'UNCONVERGED_CLAY_PLASTICITY', 'UNCONVERGED_CONCRETE_PLASTICITY', 'UNCONVERGED_CREEP_PLASTICITY', 'UNCONVERGED_DRUCKER_PRAGER_PLASTICITY', 'UNCONVERGED_FOAM_PLASTICITY', 'UNCONVERGED_HYPERELASTICITY', 'UNCONVERGED_METAL_PLASTICITY', 'UNCONVERGED_MOHR_COULOMB_PLASTICITY', 'UNDEFINED_INVARIANT', 'UNDEFINED_POSITION', 'UNDEFORMED', 'UNIFORM', 'UNION', 'UNKNOWNAXIS', 'UNKNOWNPLANE', 'UNKNOWN_ANALYSIS_CODE', 'UNKNOWN_DIMENSION', 'UNRESOLVED_INITIAL_OVERCLOSURES', 'USER', 'USER_SPECIFIED', 'USER_SUBROUTINE', 'USER_SUBROUTINE_REQUEST', 'USE_BOTTOM', 'USE_BOTTOM_AND_TOP', 'USE_ENVELOPE', 'USE_TOP', 'UserDataType', 'VAN_DER_WALLS_STRETCHES_LOCKING', 'VECTOR', 'VertexArray', 'VertexArrayType', 'VertexType', 'ViewCutOptionsType', 'ViewCutType', 'WEDGE15', 'WEDGE6', 'WHOLE_ELEMENT', 'WHOLE_MODEL', 'WHOLE_PART_INSTANCE', 'WHOLE_REGION', 'WIRE', 'XAXIS', 'XYDataType', 'XYPLANE', 'XZPLANE', 'YAXIS', 'YZPLANE', 'ZAXIS', 'ZERO', '__builtins__', '__doc__', '__name__', '__package__', '_printNumberOfGMs', '_printNumberOfMeshes', 'acos', 'acosh', 'append', 'array', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'avg', 'backwardCompatibility', 'butterworthFilter', 'ceil', 'chebyshev1Filter', 'chebyshev2Filter', 'closeOdb', 'combine', 'complexImag', 'complexMagnitude', 'complexPhase', 'complexReal', 'copyrightYear', 'copysign', 'cos', 'cosh', 'currentAvg', 'currentMax', 'currentMin', 'currentRng', 'decimateFilter', 'degreeToRadian', 'degrees', 'differentiate', 'e', 'erf', 'erfc', 'exp', 'exp10', 'expm1', 'fabs', 'factorial', 'fit', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'getDefaultMathModule', 'hypot', 'integrate', 'interpolate', 'isStudentEdition', 'isUpgradeRequiredForOdb', 'isinf', 'isnan', 'landmark', 'ldexp', 'lgamma', 'linearize', 'log', 'log10', 'log1p', 'majorVersion', 'maxEnvelope', 'minEnvelope', 'minorVersion', 'modf', 'monitorManager', 'normalize', 'odbVersion', 'openOdb', 'partInit', 'pi', 'pow', 'power', 'printMessage', 'radianToDegree', 'radians', 'registerDefaultMathModule', 'rng', 'sae1000Filter', 'sae100Filter', 'sae180Filter', 'sae600Filter', 'sae60Filter', 'saeFilter', 'saeGeneralFilter', 'sbFilter', 'sin', 'sineButterworthFilter', 'sinh', 'smooth', 'smooth2', 'sqrt', 'srss', 'sum', 'swap', 'tan', 'tanh', 'trunc', 'truncate', 'truncateOdb', 'updateVersion', 'upgradeOdb', 'vectorMagnitude', 'version']
cliCommand("""dir(p.edges)""")
#: ['__add__', '__class__', '__cmp__', '__delattr__', '__delitem__', '__delslice__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__init__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setitem__', '__setslice__', '__sizeof__', '__str__', '__subclasshook__', 'findAt', 'getBoundingBox', 'getByBoundingBox', 'getByBoundingCylinder', 'getByBoundingSphere', 'getClosest', 'getMask', 'getSequenceFromMask', 'index', 'pointsOn']
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=OFF, 
    constraints=OFF, connectors=OFF, engineeringFeatures=OFF, 
    adaptiveMeshConstraints=ON)
mdb.models['Model-1'].StaticStep(name='Step-1', previous='Initial')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='Step-1')
mdb.models['Model-1'].FieldOutputRequest(name='F-Output-2', 
    createStepName='Step-1', variables=('CSTRESS', ), timeInterval=1e-05)
mdb.saveAs(pathName='Z:/Documents/GitHub/abaqus_python_ws2023/unit_1/test2')
#: The model database has been saved to "Z:\Documents\GitHub\abaqus_python_ws2023\unit_1\test2.cae".
import job
mdb.models['Model-1'].keywordBlock.synchVersions(storeNodesAndElements=False)
mdb.models['Model-1'].keywordBlock.setValues(edited = 0)
session.viewports['Viewport: 1'].setValues(displayedObject=None)
session.viewports['Viewport: 1'].view.setValues(width=1.92748, height=1.17644, 
    viewOffsetX=-0.0135017, viewOffsetY=0.00365093)
p = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(nearPlane=144.187, 
    farPlane=152.83, width=132.925, height=81.131, viewOffsetX=13.9297, 
    viewOffsetY=-1.42417)
session.viewports['Viewport: 1'].setValues(displayedObject=None)
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=200.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.rectangle(point1=(-39.1272354125977, 21.8367309570313), point2=(
    31.547607421875, -23.061222076416))
s.CircleByCenterPerimeter(center=(-14.0325469970703, -4.59183692932129), 
    point1=(-2.04855346679688, 3.26530456542969))
s.FilletByRadius(radius=2.0, curve1=g.findAt((-39.127235, -0.612246)), 
    nearPoint1=(-39.0248107910156, 17.0408096313477), curve2=g.findAt((
    -3.789814, 21.836731)), nearPoint2=(-35.5422821044922, 21.8367309570313))
mdb.models['Model-1'].sketches.changeKey(fromName='__profile__', 
    toName='Sketch-1')
s.unsetPrimaryObject()
p = mdb.models['Model-1'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
s1 = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=200.0)
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=STANDALONE)
s1.sketchOptions.setValues(gridOrigin=(-4.83155319355495, 0.429493638501238))
#: Warning: Grid center was moved to the sketch center.
s1.retrieveSketch(sketch=mdb.models['Model-1'].sketches['Sketch-1'])
session.viewports['Viewport: 1'].view.fitView()
#: Info: 6 entities copied from Sketch-1.
p = mdb.models['Model-1'].Part(name='Part-2', dimensionality=THREE_D, 
    type=DEFORMABLE_BODY)
p = mdb.models['Model-1'].parts['Part-2']
p.BaseShellExtrude(sketch=s1, depth=20.0)
s1.unsetPrimaryObject()
p = mdb.models['Model-1'].parts['Part-2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
del mdb.models['Model-1'].sketches['__profile__']
session.viewports['Viewport: 1'].view.setValues(nearPlane=142.675, 
    farPlane=228.172, width=124.583, height=76.0396, viewOffsetX=1.85278, 
    viewOffsetY=-3.46736)
session.viewports['Viewport: 1'].view.setValues(nearPlane=157.549, 
    farPlane=218.316, width=137.572, height=83.967, cameraPosition=(87.4803, 
    -9.23448, 174.083), cameraUpVector=(-0.268507, 0.943823, -0.19262), 
    cameraTarget=(-0.227341, -2.00791, 10.8742), viewOffsetX=2.04594, 
    viewOffsetY=-3.82884)
session.viewports['Viewport: 1'].view.setValues(nearPlane=162.925, 
    farPlane=204.156, width=142.266, height=86.8322, cameraPosition=(-4.36878, 
    49.5221, 186.566), cameraUpVector=(-0.270152, 0.773791, -0.572945), 
    cameraTarget=(-2.43316, -1.84013, 8.40849), viewOffsetX=2.11575, 
    viewOffsetY=-3.95949)
session.viewports['Viewport: 1'].view.setValues(nearPlane=159.071, 
    farPlane=209.777, width=138.901, height=84.7782, cameraPosition=(25.966, 
    46.0696, 185.925), cameraUpVector=(-0.326188, 0.79522, -0.511103), 
    cameraTarget=(-2.71818, -1.6481, 9.05764), viewOffsetX=2.0657, 
    viewOffsetY=-3.86583)
session.viewports['Viewport: 1'].view.setValues(viewOffsetX=2.0671, 
    viewOffsetY=-3.86845)
cliCommand("""# a small first Abaqus Python script""")
cliCommand("""# MP, 2023-10-05""")
cliCommand("""from abaqus import *""")
cliCommand("""from abaqusConstants import *""")
cliCommand("""from caeModules import *""")
cliCommand("""import numpy as np""")
cliCommand("""# geometry parameters""")
cliCommand("""w = 50""")
cliCommand("""h = 15""")
cliCommand("""ampl = 4""")
cliCommand("""n_waves = 5""")
cliCommand("""radius = 5.""")
cliCommand("""# create x range from 0 to w with 100 points""")
cliCommand("""x = np.linspace(0,w,100)""")
cliCommand("""y = ampl * np.sin(n_waves*np.pi/w*x)""")
cliCommand("""xy_points = np.column_stack((x,y))""")
cliCommand("""Mdb()""")
#: A new model database has been created.
#: The model "Model-1" has been created.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
#: mdb
cliCommand("""# create sketch and draw lines and spline""")
cliCommand("""s = mdb.models['Model-1'].ConstrainedSketch(name='my_sketch',
                                            sheetSize=200.0)""")
cliCommand("""s.Line(point1=(0,-h), point2=(0,0))""")
#: mdb.models['Model-1'].sketches['my_sketch'].geometry.findAt((0.0, -7.5),)
cliCommand("""s.Line(point1=(w,-h), point2=(w,0))""")
#: mdb.models['Model-1'].sketches['my_sketch'].geometry.findAt((50.0, -7.5),)
cliCommand("""s.Line(point1=(0,-h), point2=(w,-h))""")
#: mdb.models['Model-1'].sketches['my_sketch'].geometry.findAt((25.0, -15.0),)
cliCommand("""s.Spline(xy_points)""")
#: mdb.models['Model-1'].sketches['my_sketch'].geometry.findAt((12.1510448909651, -2.50199727897086),)
session.viewports['Viewport: 1'].setValues(displayedObject=None)
s = mdb.models['Model-1'].ConstrainedSketch(name='__edit__', 
    objectToCopy=mdb.models['Model-1'].sketches['my_sketch'])
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
s1 = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=200.0)
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=STANDALONE)
s1.sketchOptions.setValues(gridOrigin=(25.0, -5.50001966953278))
#: Warning: Grid center was moved to the sketch center.
s1.retrieveSketch(sketch=mdb.models['Model-1'].sketches['my_sketch'])
session.viewports['Viewport: 1'].view.fitView()
#: Info: 4 entities copied from my_sketch.
p = mdb.models['Model-1'].Part(name='waves', dimensionality=TWO_D_PLANAR, 
    type=DEFORMABLE_BODY)
p = mdb.models['Model-1'].parts['waves']
p.BaseShell(sketch=s1)
s1.unsetPrimaryObject()
p = mdb.models['Model-1'].parts['waves']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
del mdb.models['Model-1'].sketches['__profile__']
session.viewports['Viewport: 1'].view.setValues(nearPlane=104.951, 
    farPlane=109.026, width=62.7104, height=38.2754, viewOffsetX=0.928965, 
    viewOffsetY=0.239164)
session.viewports['Viewport: 1'].setColor(globalTranslucency=True)
#: Coordinates of vertex 3 :0.,0.,0.
p = mdb.models['Model-1'].parts['waves']
p.DatumPlaneByPrincipalPlane(principalPlane=XZPLANE, offset=0.0)
p = mdb.models['Model-1'].parts['waves']
f = p.faces
pickedFaces = f.findAt(((39.797882, -7.620625, 0.0), ))
d1 = p.datums
p.PartitionFaceByDatumPlane(datumPlane=d1[2], faces=pickedFaces)
session.viewports['Viewport: 1'].view.setValues(nearPlane=77.6904, 
    farPlane=136.287, width=54.2137, height=33.0894, viewOffsetX=-0.242008, 
    viewOffsetY=-0.0397904)
p = mdb.models['Model-1'].parts['waves']
f1, e, d2 = p.faces, p.edges, p.datums
t = p.MakeSketchTransform(sketchPlane=f1.findAt(coordinates=(7.383381, 
    -0.833704, 0.0), normal=(0.0, 0.0, 1.0)), sketchPlaneSide=SIDE1, origin=(
    25.0, -7.932046, 0.0))
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=104.4, gridSpacing=2.61, transform=t)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=SUPERIMPOSE)
p = mdb.models['Model-1'].parts['waves']
p.projectReferencesOntoSketch(sketch=s, filter=COPLANAR_EDGES)
s.Line(point1=(-25.0, -1.305), point2=(25.5167541503906, -0.931505139831543))
s.CoincidentConstraint(entity1=v.findAt((-25.0, -1.305)), entity2=g.findAt((
    -25.0, 0.432046)), addUndoState=False)
p = mdb.models['Model-1'].parts['waves']
f = p.faces
pickedFaces = f.findAt(((7.383381, -0.833704, 0.0), ))
e1, d1 = p.edges, p.datums
p.PartitionFaceBySketch(faces=pickedFaces, sketch=s)
s.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__profile__']
session.viewports['Viewport: 1'].view.setValues(nearPlane=77.1254, 
    farPlane=136.852, width=72.0805, height=43.9944, viewOffsetX=0.870509, 
    viewOffsetY=1.40029)
session.viewports['Viewport: 1'].setColor(globalTranslucency=False)
